<MyLayout>
    id: parent_layout

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Image:
            id: my_image
            source: ""

        # FileChooserIconView:
        #     id: filechooser
        #     on_selection: parent_layout.selected(filechooser.selection)
        FileChooserListView:
            id: filechooser
            on_selection: parent_layout.selected(filechooser.selection)